# This file was generated by @liquid-labs/sdlc-projects-workflow-node-build. Refer
# to https://npmjs.com/package/@liquid-labs/sdlc-projects-workflow-node-build for
# further details

SRC:=src
DIST:=dist
TEST_STAGING:=test-staging
QA:=qa
