# This file was generated by @liquid-labs/sdlc-projects-workflow-node-build. Refer
# to https://npmjs.com/package/@liquid-labs/sdlc-projects-workflow-node-build for
# further details

.DEFAULT_GOAL:=all

.PRECIOUS: $(PRECIOUS_TARGETS)

build: $(BUILD_TARGETS)
.PHONY+= build

all: build doc
.PHONY+= all

doc: $(DOC_TARGETS)
.PHONY+= doc

lint: $(LINT_TARGETS)
lint-fix: $(LINT_FIX_TARGETS)
.PHONY+=lint lint-fix

test: $(TEST_TARGETS)
.PHONY+= test

qa: test lint
.PHONY+=qa

.PHONY: $(.PHONY)
